apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/eliegershem/dataloop-assignment-k8s.git
    targetRevision: feature/add-k8s-infra # TODO: change to HEAD after merging k8s pr
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 